Repository eddir/corp-messenger, pull requests merged in 2022-12, with the labels that each got.

#18 add: Авторизация на фронте
  .github/workflows/deployment.yml
  .github/workflows/project-checks.yml
  frontend/.eslintrc.js
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/api/services/app.service.js
  frontend/src/assets/icons/all-chats.svg
  frontend/src/components/ChatsNavbar/index.vue
  frontend/src/components/Icon/index.vue
  frontend/src/components/InputSearch/index.vue
  frontend/src/components/Modals/EditChanelModal/index.vue
  frontend/src/components/Modals/EditChatModal/index.vue
  frontend/src/components/Navbar/index.vue
  frontend/src/components/Navbar/types.js
  frontend/src/components/index.js
  frontend/src/layouts/AuthLayout.vue
  frontend/src/layouts/MainLayout.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/store/index.js
  frontend/src/store/modules/app.js
  frontend/src/store/modules/chats.js
  frontend/src/store/modules/index.js
  frontend/src/styles/index.js
  frontend/src/styles/index.less
  frontend/src/styles/layout.less
  frontend/src/utils/helpers.js
  frontend/src/utils/register-assets.js
  frontend/src/views/Chats.vue
  frontend/src/views/Contacts.vue
  frontend/src/views/Login.vue
  frontend/src/views/MainView.vue
  frontend/src/views/Profile.vue
  frontend/src/views/Register.vue
  frontend/src/views/Settings.vue
  frontend/vue.config.js
  package-lock.json
  package.json
Labels: enhancement

#10 Спецификация REST API
  .idea/corp-messenger.iml
  .idea/deployment.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/webServers.xml
  .postman/api
  postman/README.md
  postman/schemas/index.yaml
Labels: documentation

#19 frontToMaster
  frontend/src/components/Navbar/index.vue
  frontend/src/store/modules/app.js
Labels: bug

#20 Mock сервер
  postman/schemas/index.yaml
Labels: enhancement

#21 Auth: Registration
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/controller/AuthController.java
  backend/src/main/java/com/example/backend/controller/ChatController.java
  backend/src/main/java/com/example/backend/controller/UserController.java
  backend/src/main/java/com/example/backend/dto/auth/AuthenticationRequestDto.java
  backend/src/main/java/com/example/backend/dto/auth/AuthenticationResponseDto.java
  backend/src/main/java/com/example/backend/dto/company/CompanyResponseDto.java
  backend/src/main/java/com/example/backend/dto/user/UserRequestDto.java
  backend/src/main/java/com/example/backend/dto/user/UserResponseDto.java
  backend/src/main/java/com/example/backend/entities/Chat.java
  backend/src/main/java/com/example/backend/entities/Company.java
  backend/src/main/java/com/example/backend/entities/Member.java
  backend/src/main/java/com/example/backend/entities/PrimaryKey.java
  backend/src/main/java/com/example/backend/entities/Profile.java
  backend/src/main/java/com/example/backend/entities/User.java
  backend/src/main/java/com/example/backend/repositories/ChatRepository.java
  backend/src/main/java/com/example/backend/repositories/CompanyRepository.java
  backend/src/main/java/com/example/backend/repositories/MemberRepository.java
  backend/src/main/java/com/example/backend/repositories/UserRepository.java
  backend/src/main/java/com/example/backend/security/SecurityConfig.java
  backend/src/main/java/com/example/backend/services/ChatService.java
  backend/src/main/java/com/example/backend/services/CompanyService.java
  backend/src/main/java/com/example/backend/services/MemberService.java
  backend/src/main/java/com/example/backend/services/UserService.java
  docker-compose.yml
Labels: enhancement

#25 add: прикрутил апи для регистрации + валидация формы
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/services/app.service.js
  frontend/src/api/services/user.service.js
  frontend/src/components/Navbar/index.vue
  frontend/src/helpers/localization.js
  frontend/src/helpers/parseJWT.js
  frontend/src/store/modules/app.js
  frontend/src/views/Profile.vue
  frontend/src/views/Register.vue
Labels: enhancement
